//import { cloneDeep } from "lodash";
// ========================================
const WALL_POST_PUBLISH = "WALL-POST-PUBLISH";
const TEXTAREA_EDIT_WALL = "TEXTAREA-EDIT-WALL";
const GET_USER = "GET-USER";
// ========================================
export const wallPostSend = () => ({ type: WALL_POST_PUBLISH });
//----------------------------
export const wallPostEdit = (text) => ({
  type: TEXTAREA_EDIT_WALL,
  text: text,
});
//----------------------------
export const getUser = (text) => ({ type: GET_USER, text });


// ========================================
//state= this._state.bodyPart

/*
"https://www.vokrug.tv/pic/person/2/b/f/4/2bf448098b7badf3b37e87c510da29bc.jpeg",
    "Anon",
    "2 jan",
    "Minsk",
    "HNAGH-11",
    "https://learn.javascript",
    */

const init = {
  // ---------------------------------------
  postsWall: [
    {
      avatarImg:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq_I0JFO2DxoAV3J-sI7ajtx0qW0Q5neaY_A&usqp=CAU",
      text: "I hate my life",
      date: "27.01.21",
      likes: 2,
    },
    {
      avatarImg:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq_I0JFO2DxoAV3J-sI7ajtx0qW0Q5neaY_A&usqp=CAU",
      text: "Fuck de system",
      date: "23.02.21",
      likes: 5,
    },
  ],
   // ---------------------------------------
  changedText: {
    wallText: "",
  },
  // ---------------------------------------
  userData: {
    id: 'sluchainii',
    title: `ona/ono`,
    firstName: `NIKITA`,
    lastName: `TARKOVSKII`,
    gender: `OTHER`,
    email: `string(email)`,
    dateOfBirth: `1/2/1770`,
    registerDate: `string(autogenerated)`,
    phone: `string(phone number - any format)`,
    picture: `https://cdn.discordapp.com/emojis/831571946004021288.png?v=1`,
    location: 
    {
      state: `WAT`,
      street: `pushkina`,
      country: `UK`,
      timezone: `-1:00`,
      city: `Odessa`
    },
  },
};
// ========================================

function bodyReducer(state = init, action) {
  switch (action.type) {
    // --------------

    case TEXTAREA_EDIT_WALL: {
      return _textAreaEditWall(state, action);
    }
    // --------------
    case WALL_POST_PUBLISH: {
      return _postWallComment(state, action);
    }
    // --------------
       case GET_USER: {
        return _getUser(state, action);
      }
  

    // --------------
    default:
      return state;
  }
}
// ========================================

// ---------------------------------------
function _textAreaEditWall(state, action) {
  return {
    ...state,
    changedText: { ...state.changedText, wallText: action.text },
  };
}
// ---------------------------------------
function _postWallComment(state, action) {
  const curr = {
    avatarImg:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSq_I0JFO2DxoAV3J-sI7ajtx0qW0Q5neaY_A&usqp=CAU",
    text: state.changedText.wallText,
    date: "15.04.21",
    likes: 0,
  };

  return {
    ...state,
    postsWall: [...state.postsWall, curr],
    changedText: { ...state.changedText, wallText: "" },
  };
}
// ---------------------------------------
function _getUser(state, action) {
  return {
    ...state,
    userData: { ...action.text },
  };
}
// ---------------------------------------

export default bodyReducer;
